### ISSUE TITLE
`pub.yml` dependency `autocurator` is not maintained, only supports Linux and Python <=3.8

### ISSUE THREAD

**Issue by tomvothecoder** [E3SM-Project/datasm#143]
Related code:
- https://github.com/E3SM-Project/datasm/blob/28dcb6c941e0bae664828300f56c28c11c6d596a/conda-env/pub.yml#L1-L6

Issues:
- Is not being maintained -- `autocurator=0.1`is the only version available and released almost 3 years ago.
- Only supports Linux -- `noarch` is preferred
- Only supports Python <=3.8 -- not future-proof and Python 3.8 will be EOL in 2024-10
- Requires a specific version of libnetcdf that is not compatible with nco >=5.0

Downstream issues:
- Can't have a single conda environment with all datasm dependencies -- need to have a separate `proc.yml` for processing data and `pub.yml` for publishing data which adds another layer of complexity when using and developing `datasm`.
- **Eventually, there will be conflicts in the `proc.yml` because Python 3.8 is being phased out (end-of-life in 2024-10)**
  - https://devguide.python.org/versions/

Related Info:
- https://esg-publisher.readthedocs.io/en/latest/autocurator.html
- https://anaconda.org/esgf-forge/autocurator
> NOTE: you will need a functioning version of autocurator in order to run the publisher, in addition to downloading the CMOR tables. See those pages for more info. The autocurator package in the esgf-forge conda channel provides a working albeit not the most recent version of this module.

**Comment by tomvothecoder** [comment]
@TonyB9000 @chengzhuzhang I realized there was no issue GitHub issue for this. I would say this is a high priority item that @TonyB9000 should probably address before it is too late, especially if `autocurator` is a major dependency in `datasm`.

Sasha mentioned how an Xarray implementation of similar functionality might be used as an alternative solution. I also brought this up at the recent ESGF All-Hands since this is a general dependency that other projects might use for publishing to ESGF.

**Comment by TonyB9000** [comment]
@tomvothecoder @chengzhuzhang Correct.  My publication procedure is entirely dependent upon the ESGF-maintained "esgpublish", which apparently invokes Autocurator as part of its processing, and Sasha maintains esgpublish (and esgunpublish).

I should probably dive into esgpublish sometime - just to understand its operations.  The actual "publication" step (I believe) merely updates esgf datanode tables with the "mapfile" (file hashes, pub-paths) of the material to be published - but autocurator conducts some sort of validation of the data - I have no idea what it does.
